# GitHub Actions workflow example to run Checkov on Terraform
name: IaC Scan

on:
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov -d .
